# Generated by Django 2.2.5 on 2020-02-17 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('population', models.PositiveIntegerField()),
                ('land_area', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GunViolence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('date', models.DateField()),
                ('desc', models.CharField(max_length=1024)),
                ('type', models.CharField(max_length=1024)),
                ('guns', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=40.102)),
                ('longitude', models.FloatField(default=-88.2272)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gunviolence.City')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('population', models.PositiveIntegerField()),
                ('land_area', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.FloatField(default=1.0)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='gunviolence.Location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.SlugField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unknown')], max_length=8)),
                ('harm', models.SlugField(choices=[('I', 'Injured'), ('K', 'Killed'), ('U', 'Unharmed, Arrested')], max_length=8)),
                ('type', models.SlugField(choices=[('V', 'Victim'), ('S', 'Suspect')], max_length=8)),
                ('relationship', models.SlugField(choices=[('FAM', 'Family'), ('AQU', 'Aquaintance'), ('ROB', 'Armed Robbery'), ('MAS', 'Massive Shooting'), ('FRI', 'Friends'), ('GAN', 'Gang'), ('NEI', 'Neighbor')], help_text='relation to all victims', max_length=8, null=True)),
                ('involve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gunviolence.GunViolence')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gunviolence.State'),
        ),
        migrations.AddField(
            model_name='gunviolence',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gunviolence.Location'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gunviolence.State'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('latitude', 'longitude')},
        ),
    ]
