# Generated by Django 2.2.5 on 2020-04-13 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GunViolenceJson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('state', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('address', models.TextField(null=True)),
                ('n_killed', models.PositiveSmallIntegerField(null=True)),
                ('n_injured', models.PositiveSmallIntegerField(null=True)),
                ('participants', models.TextField(null=True)),
                ('characteristics', models.TextField(null=True)),
                ('guns', models.TextField(null=True)),
                ('congressional_district', models.CharField(max_length=64, null=True)),
                ('state_house_district', models.CharField(max_length=64, null=True)),
                ('state_senate_district', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GunViolence',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('city', models.CharField(max_length=64)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.TextField(null=True)),
                ('congressional_district', models.CharField(max_length=64, null=True)),
                ('state_house_district', models.CharField(max_length=64, null=True)),
                ('state_senate_district', models.CharField(max_length=64, null=True)),
                ('n_killed', models.PositiveSmallIntegerField(null=True)),
                ('n_injured', models.PositiveSmallIntegerField(null=True)),
                ('participants', models.TextField(null=True)),
                ('characteristics', models.TextField(null=True)),
                ('guns', models.TextField(null=True)),
          
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('population', models.PositiveIntegerField()),
                ('land_area', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(blank=True, max_length=64, null=True)),
                ('type', models.CharField(blank=True, max_length=64, null=True)),
                ('relationship', models.CharField(blank=True, max_length=64, null=True)),
                ('incident_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gunviolence.GunViolence')),
            ],
        ),
        migrations.AddField(
            model_name='gunviolence',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gunviolence.State'),
        ),
        migrations.CreateModel(
            name='Gun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('stolen', models.CharField(max_length=64)),
                ('incident_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gunviolence.GunViolence')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('population', models.PositiveIntegerField()),
                ('land_area', models.FloatField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gunviolence.State')),
            ],
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristic', models.CharField(max_length=512)),
                ('incident_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gunviolence.GunViolence')),
            ],
        ),
    ]
