# Generated by Django 2.2.5 on 2020-03-06 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gunviolence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GunViolenceRaw',
            fields=[
                ('incident_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('state', models.CharField(max_length=64)),
                ('city_or_county', models.CharField(max_length=64)),
                ('address', models.TextField(null=True)),
                ('n_killed', models.PositiveSmallIntegerField(null=True)),
                ('n_injured', models.PositiveSmallIntegerField(null=True)),
                ('incident_url', models.URLField(null=True)),
                ('source_url', models.URLField(null=True)),
                ('incident_url_fields_missing', models.CharField(max_length=8)),
                ('congressional_district', models.PositiveSmallIntegerField(null=True)),
                ('gun_stolen', models.CharField(max_length=64, null=True)),
                ('gun_type', models.CharField(max_length=64, null=True)),
                ('incident_characteristics', models.TextField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('location_description', models.TextField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('n_guns_involved', models.PositiveSmallIntegerField(null=True)),
                ('notes', models.TextField(null=True)),
                ('participant_age', models.TextField(null=True)),
                ('participant_age_group', models.TextField(null=True)),
                ('participant_gender', models.TextField(null=True)),
                ('participant_name', models.TextField(null=True)),
                ('participant_relationship', models.TextField(null=True)),
                ('participant_status', models.TextField(null=True)),
                ('participant_type', models.TextField(null=True)),
                ('sources', models.URLField(null=True)),
                ('state_house_district', models.PositiveSmallIntegerField(null=True)),
                ('state_senate_district', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='gunviolence',
            name='location',
        ),
        migrations.AddField(
            model_name='gunviolence',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gunviolence.City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gunviolence',
            name='latitude',
            field=models.FloatField(default=40.102),
        ),
        migrations.AddField(
            model_name='gunviolence',
            name='longitude',
            field=models.FloatField(default=-88.2272),
        ),
        migrations.AddField(
            model_name='gunviolence',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gunviolence.State'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
