# Generated by Django 2.2.5 on 2020-02-29 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gunviolence', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gunviolence',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='gunviolence',
            name='guns',
        ),
        migrations.RemoveField(
            model_name='gunviolence',
            name='type',
        ),
        migrations.AddField(
            model_name='gunviolence',
            name='note',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='gunviolence',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gunviolence.Location'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Male'), (1, 'Female')]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='harm',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Killed'), (1, 'Injured'), (2, 'Unharmed'), (3, 'Arrested')]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='relationship',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Family'), (1, 'Drive by - Random victims'), (2, 'Aquaintance'), (3, 'Significant others - current or former'), (4, 'Armed Robbery'), (5, 'Gang vs Gang'), (6, 'Mass shooting - Random victims'), (7, 'Mass shooting - Perp Knows Victims'), (8, 'Friends'), (9, 'Neighbor'), (10, 'Co-worker'), (11, 'Home Invasion - Perp Does Not Know Victim'), (12, 'Home Invasion - Perp Knows Victim')], help_text='relation to all victims', null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Victim'), (1, 'Subject-Suspect')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gunviolence.Location'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='IncidentCharacteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristic', models.CharField(choices=[(0, 'Shot - Wounded/Injured'), (1, 'Shot - Dead (murder, accidental, suicide)'), (2, 'Shots Fired - No Injuries'), (3, 'Bar/club incident - in or around establishment'), (4, 'Suicide^'), (5, 'Murder/Suicide'), (6, 'Attempted Murder/Suicide (one variable unsuccessful)'), (7, 'Domestic Violence'), (8, 'Mass Shooting (4+ victims injured or killed excluding the subject/suspect/perpetrator, one location)'), (9, 'Drive-by (car to street, car to car)'), (10, 'Gang involvement'), (11, 'Home Invasion'), (12, 'Home Invasion - Resident killed'), (13, 'Officer Involved Incident'), (14, 'Officer Involved Shooting - Officer shot'), (15, 'Officer Involved Shooting - Officer killed'), (16, 'Officer Involved Shooting - subject/suspect/perpetrator shot'), (17, 'Officer Involved Shooting - subject/suspect/perpetrator suicide at standoff'), (18, 'Spree Shooting (multiple victims, multiple locations)'), (19, 'Possession of gun by felon or prohibited person'), (20, 'Institution/Group/Business'), (21, 'Officer Involved Shooting - subject/suspect/perpetrator killed'), (22, 'Animal shot/killed'), (23, 'Home Invasion - Resident injured'), (24, 'Drug involvement'), (25, 'Armed robbery with injury/death and/or evidence of DGU found'), (26, 'Mass Murder (4+ deceased victims excluding the subject/suspect/perpetrator , one location)'), (27, 'Concealed Carry License - Perpetrator'), (28, 'Possession (gun(s) found during commission of other crimes)'), (29, 'Stolen/Illegally owned gun{s} recovered during arrest/warrant'), (30, 'School Incident'), (31, 'School Shooting - university/college'), (32, 'Kidnapping/abductions/hostage'), (33, 'Car-jacking'), (34, 'Hate crime'), (35, 'House party'), (36, 'Defensive Use'), (37, 'Defensive Use - Crime occurs, victim shoots subject/suspect/perpetrator'), (38, 'Defensive Use - Victim stops crime'), (39, 'Workplace shooting (disgruntled employee)'), (40, 'Assault weapon (AR-15, AK-47, and ALL variants defined by law enforcement)'), (41, 'Brandishing/flourishing/open carry/lost/found'), (42, 'Non-Shooting Incident'), (43, 'ATF/LE Confiscation/Raid/Arrest'), (44, 'Unlawful purchase/sale'), (45, 'Accidental Shooting'), (46, 'Accidental Shooting - Death'), (47, 'BB/Pellet/Replica gun'), (48, 'Accidental Shooting - Injury'), (49, 'Under the influence of alcohol or drugs (only applies to the subject/suspect/perpetrator )'), (50, 'Accidental/Negligent Discharge'), (51, 'Gun range/gun shop/gun show shooting'), (52, 'Thought gun was unloaded'), (53, 'Child Involved Incident'), (54, 'Child injured self'), (55, 'TSA Action'), (56, 'Road rage'), (57, 'Gun(s) stolen from owner'), (58, 'Home Invasion - No death or injury'), (59, 'School Shooting - elementary/secondary school'), (60, 'Implied Weapon'), (61, 'Officer Involved Shooting - Shots fired, no injury'), (62, 'Accidental Shooting at a Business'), (63, 'Self-Inflicted (not suicide or suicide attempt - NO PERP)'), (64, 'Concealed Carry License - Victim'), (65, 'Criminal act with stolen gun'), (66, 'Suicide - Attempt'), (67, 'Officer Involved Incident - Weapon involved but no shots fired'), (68, 'Gun at school, no death/injury - elementary/secondary school'), (69, 'Gun at school, no death/injury - university/college'), (70, 'Non-Aggression Incident'), (71, 'Home Invasion - subject/suspect/perpetrator injured'), (72, 'Defensive Use - WITHOUT a gun'), (73, 'Cleaning gun'), (74, 'Child picked up & fired gun'), (75, 'Child killed by child'), (76, 'Police Targeted'), (77, 'Home Invasion - subject/suspect/perpetrator killed'), (78, 'Defensive Use - Stand Your Ground/Castle Doctrine established'), (79, 'Hunting accident'), (80, 'Pistol-whipping'), (81, 'Child killed self'), (82, 'Sex crime involving firearm'), (83, 'Playing with gun'), (84, 'Child injured by child'), (85, 'Officer Involved Shooting - subject/suspect/perpetrator unarmed'), (86, 'Shots fired, no action (reported, no evidence found)'), (87, 'ShotSpotter'), (88, 'Defensive Use - Good Samaritan/Third Party'), (89, 'Child killed (not child shooter)'), (90, 'Gun shop robbery or burglary'), (91, 'Shootout (where VENN diagram of shooters and victims overlap)'), (92, 'Guns stolen from law enforcement'), (93, 'Officer Involved Shooting - subject/suspect/perpetrator surrender at standoff'), (94, 'LOCKDOWN/ALERT ONLY: No GV Incident Occurred Onsite'), (95, 'Defensive Use - Shots fired, no injury/death'), (96, 'Defensive use - No shots fired'), (97, 'Officer Involved Shooting - Bystander shot'), (98, 'Officer Involved Shooting - Bystander killed'), (99, 'Child injured (not child shooter)'), (100, 'Gun buy back action'), (101, 'Child with gun - no shots fired'), (102, 'Officer Involved Shooting - Accidental discharge - no injury required'), (103, 'Officer Involved Shooting - subject/suspect/perpetrator suicide by cop'), (104, 'Terrorism Involvement'), (105, 'Ghost gun'), (106, 'Mistaken ID (thought it was an intruder/threat, was friend/family)'), (107, 'Political Violence'), (108, 'NAV')], max_length=1024)),
                ('count', models.PositiveIntegerField(default=0)),
                ('city', models.ManyToManyField(to='gunviolence.City')),
                ('state', models.ManyToManyField(to='gunviolence.State')),
            ],
        ),
        migrations.AddField(
            model_name='gunviolence',
            name='characteristic',
            field=models.ManyToManyField(to='gunviolence.IncidentCharacteristic'),
        ),
    ]
