# Generated by Django 2.2.5 on 2020-04-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gunviolence', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Characteristic',
        ),
    ]
