# Generated by Django 2.2.5 on 2020-03-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gunviolence', '0002_auto_20200306_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gunviolenceraw',
            name='incident_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
